name = "Earthmodded"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b1cdace9003758ef3cd0f9d9b7525fb2312eaf4b099620f8cc22506bf1df694c"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.248"
