name = "Earthmodded"
author = "kelseykuri486"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9e7de6f7479fae21d4bfa13fa26969bcc3db985a26a826e30c920b77ea781510"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.248"
