name = "Earthmodded"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "36b47c2933efd7e65b44784409d62f8d8b132a368f85def8abe2b7858059a2c8"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.248"
